import 'server-only'
import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'

export type TutorClass={id:string; subjectName:string|null; studentName:string; studentGrade:string|null; parentName:string|null; parentPhone:string|null; mode:string; location:string|null; status:string; tuitionFee:number|null; scheduleNotes:string|null; requirements:string|null; notes:string|null}
export async function requireTutorId(){const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error('Unauthorized'); const {data,error}=await supabase.from('tutors').select('id,active').eq('profile_id',user.id).single(); if(error||!data||!data.active) throw new Error('Unauthorized'); return data.id as string}
function mapClass(c:any):TutorClass{return {id:c.id,subjectName:(Array.isArray(c.subjects)?c.subjects[0]:c.subjects)?.name??null,studentName:c.student_name,studentGrade:c.student_grade,parentName:c.parent_name,parentPhone:c.parent_phone,mode:c.mode,location:c.location,status:c.status,tuitionFee:c.tuition_fee,scheduleNotes:c.schedule_notes,requirements:c.requirements,notes:c.notes}}
export async function listAssignedClasses(){const tutorId=await requireTutorId(); const admin=createAdminClient(); const {data,error}=await admin.from('classes').select('id,student_name,student_grade,parent_name,parent_phone,mode,location,status,tuition_fee,schedule_notes,requirements,notes,subjects(name)').eq('tutor_id',tutorId).order('updated_at',{ascending:false}); if(error) throw new Error(error.message); return (data??[]).map(mapClass)}
export async function listOpenClasses(){await requireTutorId(); const admin=createAdminClient(); const {data,error}=await admin.from('classes').select('id,student_name,student_grade,mode,location,status,tuition_fee,schedule_notes,requirements,notes,subjects(name)').eq('status','open').is('tutor_id',null).order('updated_at',{ascending:false}); if(error) throw new Error(error.message); return (data??[]).map((c:any)=>({...mapClass(c),parentName:null,parentPhone:null}))}
export async function getAssignedClass(classId:string){const tutorId=await requireTutorId(); const admin=createAdminClient(); const {data,error}=await admin.from('classes').select('id,student_name,student_grade,parent_name,parent_phone,mode,location,status,tuition_fee,schedule_notes,requirements,notes,subjects(name)').eq('id',classId).eq('tutor_id',tutorId).maybeSingle(); if(error) throw new Error(error.message); return data?mapClass(data):null}
