export const tutors = [
  {
    id: 1,
    name: "Nguyễn Nguyên Anh",
    role: "Founder & Gia sư Tin học / Toán",
    subjects: ["Toán học", "Tin học lập trình"],
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/NguyenAnh-XPZSf8rgFny6gCo35jsAH5NZhUfQN5.jpg",
    avatarPosition: "object-top",
    education: "ĐH Khoa học Tự nhiên, ĐHQG-HCM — Cử nhân Khoa học và CN Vật liệu (Bán dẫn) · GPA 8.0",
    narrative: "Em bắt đầu hành trình với tin học từ lớp Chuyên Tin tại THPT Gia Định TP.HCM. Năm 2021, em đạt Giải Nhất cấp Quận và Giải Ba cấp Thành phố Hồ Chí Minh môn Tin học. Năm 2024, em được chọn vào Vòng tuyển Đội tuyển Quốc gia môn Tin học. Không dừng lại ở lý thuyết, em đã giành Giải Ba tại SEAL Hackathon Fall 2025 (bảng AI Innovation) và 2nd Runner-up tại WebDev Adventure của CLB Web - Đại học Công nghệ Thông tin, ĐHQG TP.HCM. Hiện tại, em đang là giáo viên Robotics tại Trung tâm Bi Seam Robotics, nơi em giảng dạy lập trình robot cho các em nhỏ.",
    keyHighlights: [
      "Vòng chọn Đội tuyển Quốc gia Tin học 2024",
      "Giải Ba HSG Tin học cấp TP.HCM 2021",
      "Giải Ba SEAL Hackathon — AI Innovation",
      "Giáo viên Robotics tại Bi Seam",
    ],
    experience: "2+ năm",
    students: "30+",
    rating: "4.9/5",
    approach: "Em xem mỗi buổi học như một tấm canvas trắng. Thay vì giảng theo khuôn mẫu, em lồng ghép các ví dụ từ Marvel hay Iron Man vào bài giảng, biến code thành câu chuyện. Học sinh không chỉ viết chương trình mà còn tự tay xây dựng sản phẩm — từ robot điều khiển được đến ứng dụng web thực tế. Lộ trình được cá nhân hóa hoàn toàn, dựa trên kinh nghiệm thực tiễn từ công việc giảng dạy Robotics của em tại Bi Seam.",
    languages: ["Python", "C++", "Scratch", "HTML/CSS", "React"],
    contact: {
      phone: "0899 736 669",
      email: "tameanhanh@gmail.com",
    },
  },
  {
    id: 2,
    name: "Nguyễn Lê Thiện",
    role: "Gia sư Vật lý / Toán",
    subjects: ["Vật lý", "Toán học"],
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/thien-296Ar7kDTpat2qRpLAam23lbAfJsX9.jpg",
    avatarPosition: "object-top",
    education: "ĐH Khoa học Tự nhiên, ĐHQG-HCM — Cử nhân CN Vật liệu (Bán dẫn) · GPA 8.5/10",
    narrative: "Em giữ điểm trung bình 9.6+ suốt 4 năm THCS và 9.0+ trong 3 năm THPT tại Trường Chuyên Trần Hưng Đạo (Bình Thuận). Em từng đạt giải HSG môn Lý cấp trường lẫn cấp huyện, đồng thời nhận Học bổng khuyến khích học tập môn Lý lớp 12. Tại đại học, các môn Vật lý Đại cương, Vật lý Hiện đại của em đều đạt trên 9.5. Hiện tại, em có kinh nghiệm dạy gia sư cho học sinh từ lớp 6 đến lớp 11.",
    keyHighlights: [
      "ĐTB THCS 9.6+ | THPT 9.0+",
      "Học sinh chuyên Lý — THPT Chuyên Trần Hưng Đạo",
      "Giải HSG Lý cấp trường & huyện",
      "ĐTB môn Lý đại học 9.5+",
    ],
    experience: "2+ năm",
    students: "20+",
    rating: "4.9/5",
    approach: "Em không chấp nhận việc học vẹt. Em dành thời gian vẽ lại bức tranh vật lý trên một tấm canvas khái niệm: từ nguyên lý cơ bản đến hiện tượng thực tế, mỗi định luật được liên kết với ví dụ trực quan. Phương pháp này phù hợp cho cả học sinh mất gốc cần xây lại nền tảng lẫn học sinh khá giỏi muốn đào sâu hơn.",
    contact: {
      phone: "0945 245 977",
      email: "nglethien2006cv@gmail.com",
    },
  },
  {
    id: 3,
    name: "Hồ Hải Vy",
    role: "Gia sư Vật lý",
    subjects: ["Vật lý"],
    avatar: "",
    avatarPosition: "object-center",
    education: "ĐH Khoa học Tự nhiên, ĐHQG-HCM — Chuyên ngành CN Vật liệu Bán dẫn · GPA Lý đại cương 9.5+",
    narrative: "Tôi đã xây dựng được một nền tảng vật lý cực kỳ vững chắc với chuỗi thành tích xuất sắc từ những năm tháng cấp 3 cho đến bậc Đại học. Với kinh nghiệm trong các đội tuyển học sinh giỏi và giải toán nhanh trên máy tính cầm tay, tôi mong muốn truyền đạt phương pháp tư duy sắc bén, giúp các em học sinh phá vỡ rào cản sợ môn Lý.",
    keyHighlights: [
      "Giải Nhì HSG môn Vật lý cấp Trường",
      "Giải Khuyến khích HSG môn Vật lý cấp Tỉnh",
      "Điểm Lý đại cương 1 bậc Đại học đạt 9.5+",
    ],
    experience: "2+ năm",
    students: "12+",
    rating: "4.8/5",
    approach: "Kết hợp giữa việc hiểu sâu bản chất hiện tượng và rèn luyện kỹ năng tính toán tốc độ cao, ứng dụng các phương pháp bấm máy tính cầm tay tối ưu nhất.",
    contact: {
      phone: "0816 345 214",
      email: "hohaivy2007@gmail.com",
    },
  },
  {
    id: 4,
    name: "Nguyễn Ngọc Minh Châu",
    role: "Gia sư Toán / Hóa học",
    subjects: ["Toán học", "Hóa học"],
    avatar: "",
    avatarPosition: "object-center",
    education: "ĐH Giao thông Vận tải TP.HCM — Chuyên ngành Logistics & Quản lý chuỗi cung ứng · GPA 3.70/4.0",
    narrative: "Sở hữu nền tảng vững chắc ở các môn Khoa học Tự nhiên, tôi luôn tin rằng việc học Toán và Hóa không nên bị gò bó trong việc học thuộc công thức máy móc. Tôi mong muốn các em học sinh hiểu rõ bản chất cốt lõi và phát triển tư duy logic.",
    keyHighlights: [
      "Học sinh giỏi cấp Tỉnh môn Hóa học (Lớp 11)",
      "Học sinh giỏi cấp Thành phố môn Toán (Lớp 9)",
      "GPA Đại học đạt mức xuất sắc 3.70",
    ],
    experience: "2+ năm",
    students: "15+",
    rating: "4.9/5",
    approach: "Hệ thống hóa kiến thức một cách khoa học và trực quan, gắn liền lý thuyết khô khan với các ví dụ thực tế sinh động để bài học trở nên gần gũi.",
    contact: {
      phone: "0849 880 552",
      email: "ngminhchau552@gmail.com",
    },
  },
  {
    id: 5,
    name: "Nguyễn Trọng Phúc",
    role: "Gia sư Hóa học / KHTN",
    subjects: ["Hóa học"],
    avatar: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/phuc-mEzRSPDYRQDlJbmroFFfVWBsYg3a8s.jpg",
    avatarPosition: "object-[50%_20%]",
    education: "ĐH Khoa học Tự nhiên, ĐHQG-HCM — CN Vật liệu Polymer Composite · Điểm đầu vào 25đ",
    narrative: "Em tốt nghiệp THPT Thuận Hưng với loại Giỏi và điểm trung bình môn Hóa trên 9.0 từ lớp 8 đến lớp 12. Em từng đạt Giải Ba HSG Hóa lý thuyết cấp Thành phố năm lớp 9, cùng các giải Khuyến khích ở cấp Quận và Thành phố cho cả phần lý thuyết lẫn thực hành. Ngoài Hóa học, em còn tham gia HSG KHTN tiếng Anh và HSG Tiếng Anh cấp Thành phố. Hiện tại, em đã giúp nhiều học sinh mất gốc thi đỗ vào các trường THPT.",
    keyHighlights: [
      "Tốt nghiệp THPT loại Giỏi — ĐTB 9.0+",
      "Giải Ba HSG Hóa lý thuyết cấp Thành phố",
      "ĐTB môn Hóa 9.0+ suốt 5 năm",
      "Kinh nghiệm giúp học sinh mất gốc thi đỗ THPT",
    ],
    experience: "2+ năm",
    students: "25+",
    rating: "4.9/5",
    approach: "Em tin rằng hóa học không nên là môn học thuộc lòng. Em kết hợp lý thuyết với hình ảnh thực tế, biến mỗi phản ứng thành một bức tranh sinh động trên canvas kiến thức. Với sự nhiệt tình và tình yêu dành cho trẻ, em đặc biệt giỏi giúp những học sinh đang chật vật tìm lại nền tảng và sự tự tin.",
    contact: {
      phone: "0393 404 842",
      email: "trongphuc20075858@gmail.com",
    },
  },
  {
    id: 6,
    name: "Quách Thanh Tùng",
    role: "Gia sư Toán / Vật lý / Hóa học",
    subjects: ["Toán học", "Vật lý", "Hóa học"],
    avatar: "",
    avatarPosition: "object-center",
    education: "ĐH Khoa học Tự nhiên, ĐHQG-HCM — Chuyên ngành Công nghệ Vật liệu · Toán cao cấp 8.9",
    narrative: "Tôi đã xây dựng một nền tảng vững chắc cho các môn tự nhiên xuyên suốt thời gian từ bậc trung học đến đại học. Với tinh thần trách nhiệm và sự kiên nhẫn của mình, tôi mong muốn tạo ra một môi trường học tập tuyệt vời hướng tới sự logic, dễ hiểu.",
    keyHighlights: [
      "Ba năm học sinh giỏi THPT Phú Nhận",
      "Tổng điểm trung bình 3 năm THPT đạt 8.8",
      "Điểm kết thúc môn Toán cao cấp đạt 8.9",
    ],
    experience: "2+ năm",
    students: "22+",
    rating: "4.9/5",
    approach: "Dạy học sinh cách tự đặt câu hỏi và hiểu rõ nguyên lý cốt lõi. Khuyến khích các bạn linh hoạt áp dụng kiến thức vào mọi dạng đề thi mà không theo mẫu sẵn.",
    contact: {
      phone: "0779 140 107",
      email: "quachtunqth1401@gmail.com",
    },
  },
  {
    id: 7,
    name: "Bùi Nguyễn Thúy Diễm",
    role: "Gia sư Toán học",
    subjects: ["Toán học"],
    avatar: "",
    avatarPosition: "object-center",
    education: "ĐH Ngân hàng TP.HCM — Chuyên ngành Hệ thống thông tin quản lý · GPA 3.5/4.0",
    narrative: "Là một gia sư tận tâm, tôi luôn đồng hành cùng phụ huynh xây dựng lộ trình cá nhân hóa cho từng học sinh. Thấu hiểu mỗi học sinh có một tốc độ tiếp thu khác nhau, tôi chọn phương pháp truyền đạt dễ hiểu, đi sâu vào bản chất kiến thức.",
    keyHighlights: [
      "Học bổng Khuyến khích học tập Loại Xuất sắc",
      "Giúp học sinh ôn thi lớp 10 tăng từ 5.0 lên 7.25 sau 10 buổi",
      "Các học phần Toán đại cương bậc Đại học luôn đạt từ 3.5+",
    ],
    experience: "2+ năm",
    students: "25+",
    rating: "4.9/5",
    approach: "Tôi ưu tiên củng cố nền tảng vững chắc, kích thích tư duy giải quyết vấn đề và tạo động lực học tập, giúp học sinh bứt phá điểm số trong thời gian ngắn.",
    contact: {
      phone: "0377 964 589",
      email: "nguyenthuydiem2006@gmail.com",
    },
  },
  {
    id: 8,
    name: "Hồ Nguyễn Trường Vũ",
    role: "Gia sư Khoa học Tự nhiên / Toán",
    subjects: ["Toán học", "Vật lý", "Hóa học"],
    avatar: "",
    avatarPosition: "object-center",
    education: "ĐH Sư phạm TP.HCM — Chuyên ngành Sư phạm Khoa học Tự nhiên · GPA 3.54",
    narrative: "Là một giáo viên tương lai được đào tạo chuyên môn sâu, tôi luôn kiên định theo đuổi phương châm: 'Dạy bằng sự tận tâm, học bằng sự đam mê, trưởng thành bằng sự nỗ lực.'",
    keyHighlights: [
      "GPA học tập tại Đại học Sư phạm đạt 3.54",
      "Đạt 8.5 điểm môn Toán kỳ thi ĐGNL chuyên biệt",
      "ĐTB các môn cốt lõi (Toán, Lý, Hóa) đạt 9.0+",
    ],
    experience: "2+ năm",
    students: "16+",
    rating: "4.9/5",
    approach: "Áp dụng các kỹ năng nghiệp vụ sư phạm bài bản để biến các khái niệm tự nhiên khô khan thành những bài học sinh động, gần gũi. Lấy học sinh làm trung tâm.",
    contact: {
      phone: "0888 284 193",
      email: "truonqvu230707@gmail.com",
    },
  },
  {
    id: 9,
    name: "Đào Minh Hiếu",
    role: "Gia sư Toán học",
    subjects: ["Toán học"],
    avatar: "",
    avatarPosition: "object-center",
    education: "ĐH Khoa học Tự nhiên, ĐHQG-HCM — CN Công nghệ Vật liệu Bán dẫn · GPA 8.5/10",
    narrative: "Với niềm đam mê mãnh liệt dành cho những con số và tư duy logic, em sở hữu nền tảng Toán học cực kỳ vững chắc được minh chứng qua danh hiệu Thủ khoa Toán cấp THCS và hàng loạt điểm A, A+ các môn Toán bậc Đại học.",
    keyHighlights: [
      "Thủ khoa môn Toán cấp THCS",
      "Đạt giải Học sinh giỏi môn Toán cấp trường và huyện",
      "Điểm tuyệt đối A, A+ các môn Toán chuyên sâu đại học",
    ],
    experience: "2+ năm",
    students: "20+",
    rating: "4.9/5",
    approach: "Áp dụng tư duy chia nhỏ vấn đề (step-by-step). Hướng dẫn học sinh cách phân tích đề bài, tìm ra quy luật logic thay vì giải bài theo mẫu có sẵn.",
    contact: {
      phone: "0365 477 150",
      email: "daohieu0205@gmail.com",
    },
  },
  {
    id: 10,
    name: "Đỗ Trần Minh Quân",
    role: "Gia sư Sinh học",
    subjects: ["Sinh học"],
    avatar: "",
    avatarPosition: "object-center",
    education: "ĐH Quốc tế ĐHQG-HCM — Cử nhân ngành Kỹ thuật Hóa học · GPA 8.0/10",
    narrative: "Với niềm đam mê lớn dành cho thế giới tự nhiên và các cơ chế sống, tôi luôn tìm kiếm những phương pháp tiếp cận môn Sinh một cách khoa học, hệ thống.",
    keyHighlights: [
      "Giải Ba Học sinh giỏi cấp Thành phố môn Sinh học",
      "Cú đúp giải thưởng HSG TP môn Sinh học & thi Máy tính cầm tay",
      "Đạt điểm số 9.0 môn Sinh học trong kỳ thi tốt nghiệp THPT",
    ],
    experience: "2+ năm",
    students: "10+",
    rating: "4.8/5",
    approach: "Lồng ghép kỹ thuật sử dụng máy tính cầm tay để giải nhanh các bài toán sinh học, học qua hình ảnh và sơ đồ tư duy trực quan.",
    contact: {
      phone: "0976 412 152",
      email: "tpaeducation.vercel.app@gmail.com",
    },
  },
]


export const subjects = [
  {
    id: 1,
    name: "Toán học",
    icon: "Calculator",
    description: "Đại số, Hình học, Giải tích, Xác suất thống kê",
    levels: ["THCS", "THPT"],
    color: "navy",
  },
  {
    id: 2,
    name: "Tin học Lập trình",
    icon: "Code2",
    description: "Python, C++, Scratch, Tư duy thuật toán",
    levels: ["THCS", "THPT"],
    color: "gold",
  },
  {
    id: 3,
    name: "Vật lý",
    icon: "Atom",
    description: "Cơ học, Điện từ, Quang học, Nhiệt học",
    levels: ["THCS", "THPT"],
    color: "navy",
  },
  {
    id: 4,
    name: "Hóa học",
    icon: "FlaskConical",
    description: "Hóa vô cơ, Hóa hữu cơ, Phương trình phản ứng",
    levels: ["THCS", "THPT"],
    color: "gold",
  },
]



export const faqs = [
  {
    question: "Làm thế nào để đăng ký học tại TPA+?",
    answer: "Bạn có thể đăng ký bằng cách điền form liên hệ trên website, gọi điện hotline, hoặc nhắn tin qua Facebook/Zalo. Chúng tôi sẽ liên hệ tư vấn trong vòng 24h.",
  },
  {
    question: "Học phí tại TPA+ như thế nào?",
    answer: "Học phí được tính theo buổi, tùy thuộc vào môn học và cấp độ. Chúng tôi sẽ tư vấn chi tiết sau khi đánh giá trình độ học sinh. Có ưu đãi khi đăng ký theo gói.",
  },
  {
    question: "Có được học thử trước khi đăng ký không?",
    answer: "Có! TPA+ cung cấp 1 buổi học thử MIỄN PHÍ để học sinh và phụ huynh đánh giá chất lượng giảng dạy trước khi quyết định đăng ký.",
  },
  {
    question: "Gia sư có đến nhà dạy không?",
    answer: "Có, chúng tôi hỗ trợ cả hình thức Online (qua Zoom/Google Meet) và Offline (tại nhà học sinh hoặc địa điểm thỏa thuận trong khu vực Dĩ An, Thủ Đức, Làng Đại học).",
  },
  {
    question: "Lịch học có linh hoạt không?",
    answer: "Lịch học được sắp xếp linh hoạt theo thời gian của học sinh. Học sinh có thể đổi lịch với thông báo trước 24h.",
  },
  {
    question: "Phụ huynh có được cập nhật tiến độ học tập không?",
    answer: "Có! Phụ huynh sẽ nhận báo cáo tiến độ hàng tuần qua Zalo/Email, bao gồm đánh giá năng lực, điểm mạnh/yếu, và đề xuất cải thiện.",
  },
  {
    question: "TPA+ cam kết gì về chất lượng?",
    answer: "Chúng tôi cam kết: Tiến bộ rõ rệt sau 4 tuần hoặc hoàn tiền; Gia sư có trình độ và kinh nghiệm; Lộ trình học tập cá nhân hóa; Hỗ trợ giải đáp ngoài giờ học.",
  },
]

export const consultationProcess = [
  {
    step: 1,
    title: "Tiếp nhận yêu cầu",
    description: "Phụ huynh/học sinh liên hệ qua hotline, form website hoặc mạng xã hội",
    icon: "MessageCircle",
    duration: "Ngay lập tức",
  },
  {
    step: 2,
    title: "Tư vấn miễn phí",
    description: "Trao đổi về nhu cầu học tập, mục tiêu, và giới thiệu gia sư phù hợp",
    icon: "Phone",
    duration: "15-30 phút",
  },
  {
    step: 3,
    title: "Bài test đầu vào",
    description: "Đánh giá trình độ hiện tại để xây dựng lộ trình học tập cá nhân hóa",
    icon: "ClipboardCheck",
    duration: "30-45 phút",
  },
  {
    step: 4,
    title: "Buổi học thử",
    description: "1 buổi học thử MIỄN PHÍ để trải nghiệm phương pháp giảng dạy",
    icon: "BookOpen",
    duration: "30 - 60 phút",
  },
  {
    step: 5,
    title: "Xác nhận đăng ký",
    description: "Xác nhận lịch học và bắt đầu hành trình tiến bộ",
    icon: "CheckCircle2",
    duration: "Linh hoạt",
  },
]


export const commitments = [
  {
    title: "Cam kết tiến bộ",
    description: "Học sinh tiến bộ rõ rệt sau 4 tuần hoặc hoàn tiền 100%",
    icon: "TrendingUp",
  },
  {
    title: "Báo cáo định kỳ",
    description: "Phụ huynh nhận báo cáo tiến độ chi tiết hàng tuần",
    icon: "FileText",
  },
  {
    title: "Hỗ trợ 24/7",
    description: "Giải đáp thắc mắc ngoài giờ học qua Zalo/Messenger",
    icon: "HeadphonesIcon",
  },
  {
    title: "Lộ trình cá nhân",
    description: "Mỗi học sinh có lộ trình học riêng, phù hợp năng lực",
    icon: "Route",
  },
  {
    title: "Gia sư chất lượng",
    description: "100% gia sư từ các trường Đại học hàng đầu",
    icon: "GraduationCap",
  },
  {
    title: "Đổi gia sư miễn phí",
    description: "Không phù hợp? Đổi gia sư khác hoàn toàn miễn phí",
    icon: "RefreshCw",
  },
]


export const learningPaths = [
  {
    name: 'Foundation Track',
    duration: '8 weeks',
    target: 'Rebuild fundamentals with confidence',
    milestones: [
      { week: 1, content: 'Assess current level and close core knowledge gaps.' },
      { week: 3, content: 'Practice guided problem-solving with tutor feedback.' },
      { week: 6, content: 'Build independent habits through weekly review sets.' },
    ],
    outcome: 'Strong core understanding and improved study rhythm.',
  },
  {
    name: 'Acceleration Track',
    duration: '12 weeks',
    target: 'Improve school performance and exam readiness',
    milestones: [
      { week: 1, content: 'Set goals and map the highest-impact topics first.' },
      { week: 4, content: 'Strengthen speed and accuracy across common test formats.' },
      { week: 8, content: 'Apply mixed-topic drills with mistake analysis.' },
    ],
    outcome: 'Faster progress, higher confidence, and measurable score gains.',
  },
  {
    name: 'Advanced Track',
    duration: '16 weeks',
    target: 'Go deeper for competitions or advanced study',
    milestones: [
      { week: 2, content: 'Master advanced concepts beyond standard classroom scope.' },
      { week: 7, content: 'Practice complex problems with strategic solution patterns.' },
      { week: 12, content: 'Refine performance through mock challenges and review.' },
    ],
    outcome: 'Deeper mastery and stronger performance on advanced assessments.',
  },
]
